apiVersion: v1
kind: Pod
metadata:
  name: demopod
spec:
  containers:
  - name: testport8080
    image: hsa404/assignments:latest
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: port-config
          key: port
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
  imagePullSecrets:
  - name: secretdocker
